name       : haskell-foundation
version    : 0.0.20
release    : 1
source     :
    - https://hackage.haskell.org/package/foundation-0.0.20/foundation-0.0.20.tar.gz : ba6ae63a9ce0846bf942af2c3ace56600f051c61e83a0b55dd625de23a78e42d
license    : BSD-3-Clause
component  : programming.haskell
summary    : A custom prelude with no dependencies apart from base.
description: |
    A custom prelude with no dependencies apart from base.
builddeps  :
    - haskell-basement
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
