name       : haskell-foundation
version    : 0.0.25
release    : 2
source     :
    - https://hackage.haskell.org/package/foundation-0.0.25/foundation-0.0.25.tar.gz : c158550f8429be8614e832aa0b5018b29a4e5a8429118bdca5f6d7e74fe9d360
license    : BSD-3-Clause
component  : programming.haskell
summary    : A custom prelude with no dependencies apart from base.
description: |
    A custom prelude with no dependencies apart from base.
builddeps  :
    - haskell-basement-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-basement-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
